# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: expand_node.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-21T12:02:57+08:00
# @License: GNU General Public License v3.0

- name: 拷贝扩展群组的创世区块
  copy:
    src: "{{ fisco_workdir }}/agency_{{ item.name }}/group/group.{{ item.main_group_id }}.genesis"
    dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/group.{{ item.main_group_id }}.genesis"
  loop: "{{ fisco_agencies }}"
  loop_control:
    label: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/group.{{ item.main_group_id }}.genesis"
  when:
    - agency.extra_group_id is defined
    - agency.extra_group_id is truthy
    - item.main_group_id in agency.extra_group_id
    - item.create_genesis | default(false)

- name: "更新新增节点配置文件"
  template:
    src: "expand_node_deployment.ini.j2"
    dest: "{{ fisco_workdir }}/agency_{{ agency.name }}/conf/node_deployment.ini"
    mode: 0600
    backup: true

- name: "生成机构新增节点信息"
  command: "./generator --generate_all_certificates ./agency_{{ agency.name }}_node_info_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }} {{ fisco_gm_enabled | ternary('-g', '') }}"
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
  changed_when: false

- name: "添加新增节点到 {{ fisco_workdir }}/agency_{{ agency.name }}/meta/peers_{{ agency.main_group_id }}.txt"
  lineinfile:
    path: "{{ fisco_workdir }}/agency_{{ agency.name }}/meta/peers_{{ agency.main_group_id }}.txt"
    line: "{{ item.split(':')[2] }}:{{ item.split(':')[3] }}"
  loop: "{{ groups['fisco_expand_nodes'] | sort }}"
  loop_control:
    label: "{{ item.split(':')[2] }}:{{ item.split(':')[3] }}"
  when:
    - item.split(':')[0] == agency.name
    - (item.split(':')[1] | int) == agency.main_group_id

- name: "生成新增节点配置在 {{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }}"
  command: "./generator --build_install_package ./meta/peers_{{ agency.main_group_id }}.txt ./fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }} {{ fisco_gm_enabled | ternary('-g', '') }}"
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}/"
  changed_when: false

- block:
    - name: "群组扩展 | 机构 {{ agency.name }} 为现有节点初始化 {{ agency.extra_group_id }} 群组"
      command: "./generator --add_group ./meta/group.{{ item }}.genesis ./fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }}"
      args:
        chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
      changed_when: false
      loop: "{{ agency.extra_group_id }}"
      loop_control:
        label: "./generator --add_group ./meta/group.{{ item }}.genesis ./fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }}"

    - name: "群组扩展 | 机构 {{ agency.name }} 添加其它组 {{ agency.extra_group_id }} 节点信息"
      command: "./generator --add_peers ./meta/peers_{{ item }}.txt ./fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }}"
      args:
        chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
      loop: "{{ agency.extra_group_id }}"
      loop_control:
        label: "./generator --add_peers ./meta/peers_{{ item }}.txt ./fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }}"
      changed_when: false
  when:
    - agency.extra_group_id is defined
    - agency.extra_group_id is truthy

- name: 更新 listen_ip
  ini_file:
    path: "{{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }}/node_{{ item.split(':')[2] }}_{{ item.split(':')[3] }}/config.ini"
    section: "p2p"
    option: "listen_ip"
    value: "{{ item.split(':')[2] }}"
  loop: "{{ groups['fisco_expand_nodes'] | sort }}"
  loop_control:
    label: "{{ fisco_workdir }}/agency_{{ agency.name }}/fisco_deploy_agency_{{ agency.name }}_expand_{{ groups['fisco_expand_nodes'] | hash('md5') }}/node_{{ item.split(':')[2] }}_{{ item.split(':')[3] }}/config.ini"
  when: "item.split(':')[0] == agency.name"
