# @Author: Haibin Lee <haibin>
# @Date:   2020-11-11T16:56:37+08:00
# @Email:  haibin.li@newtouch.com
# @Filename: generate_genesis.yml
# @Last modified by:   haibin
# @Last modified time: 2020-12-18T17:28:26+08:00
# @License: GNU General Public License v3.0



- name: "生成群组 {{ loop_main_group_id }} 创世区块"
  command: "./generator --create_group_genesis ./group {{ fisco_gm_enabled | ternary('-g', '') }}"
  args:
    chdir: "{{ fisco_workdir }}/agency_{{ agency.name }}"
  changed_when: false

# - name: "分发创世区块到同组机构"
#   copy:
#     src: "{{ fisco_workdir }}/agency_{{ agency.name }}/group/group.{{ agency.main_group_id }}.genesis"
#     dest: "{{ fisco_workdir }}/agency_{{ item }}/meta/group.{{ agency.main_group_id }}.genesis"
#   loop: "{{ groups['fisco_agency_group_' + agency.main_group_id|quote] }}"
#   loop_control:
#     label: "{{ fisco_workdir }}/agency_{{ item }}/meta/group.{{ agency.main_group_id }}.genesis"
