@startuml

title 官方文档手动步骤

start
:安装 generator;
:generator 初始化联盟链证书;
if (机构 A) then
  :基于 generator 目录复制出机构 A 目录;
  :generator 生成机构 A 证书;
  :generator 发送链证书、机构证书、机构私钥至机构 A 目录;
  :机构 A 修改配置文件;
  :机构 A 生成并发送节点信息至机构 B 目录;
  :机构 A 生成群组 1 创世区块;
  :分发群组 1 创世区块至机构 B 目录;
  :生成机构 A 所属节点;
  :启动节点;
elseif (机构 B) then
  :基于 generator 目录复制出机构 B 目录;
  :generator 生成机构 B 证书;
  :generator 发送链证书、机构证书、机构私钥至机构 B 目录;
  :机构 B 修改配置文件;
  :机构 B 生成并发送节点证书至机构 A 目录;
  :机构 B 生成并发送节点信息至机构 A 目录;
  :生成机构 B 所属节点;
  :启动节点;
elseif (机构 C) then
  :基于 generator 目录复制出机构 C 目录;
  :generator 生成机构 C 证书;
  :generator 发送链证书、机构证书、机构私钥至机构 C 目录;
  :机构 A 发送节点 P2P 连接信息以及节点证书发送至机构 C 目录;
  :机构 C 修改配置文件;
  :机构 C 生成节点证书;
  :机构 C 生成并发送节点信息至机构 A 目录;
  :机构 C 生成群组 2 创世区块;
  :分发群组 2 创世区块至机构 A 目录;
  :生成机构 C 所属节点;
  :启动节点;
else (群组扩展)
  :群组 2 创世区块添加到机构 A 下的所有节点;
  :机构 C 节点 P2P 连接地添加到机构 A 下的所有节点;
  :停止机构 A 所有节点;
  :启动机构 A 所有节点;
endif
stop

@enduml
