@startwbs
* Ansible for FISCO BCOS 开发路线图

** 项目启动 2020.10.01
*** 完成集群初始化 2020.10.09
*** 完成机构扩展节点 2020.10.22

** 版本 2.6.x
*** 增加部署架构图的自动生成 2020.11.24
*** 增加节点配置的定制（预计在 2020.12.10 前完成）
*** 增加控制台配置对多群组的支持（预计在 2020.12.15 前完成）

** 版本 2.7.x
*** 适配 FISCO BCOS 2.7.0（预计在 2020.12.31 前完成）
**** 控制台改用 toml 配置
**** 其它可能新增的变化，需要对比官方文档。
*** 群组新增机构（预计在 2020.1.31 前完成）

@endwbs
